### ISSUE TITLE
BLCA with Silva 23S LSU database?

### ISSUE THREAD

**Issue by wolfgangrumpf** [qunfengdong/BLCA#15]
I'd be interested in knowing how I could create a BLCA-compatible database from the SILVA 23S LSU data - is this possible?

**Comment by qunfengdong** [comment]
We have never tried that. The only challenge is whether you can obtain
NCBI-format taxonomic information for the SILA 23S LSU sequences.  Once you
can do that, BLCA should work.

**Comment by dswan** [comment]
It is possible to do this. SILVA preserves the original sequence ID, so you can remap back to the NCBI taxonomy based on this, or just the species name with something like the ETE toolkit

**Comment by qunfengdong** [comment]
That's excellent suggestion. We will get it done.  Any further guidance
will be much appreciated.

**Comment by dswan** [comment]
> 
> 
> I'd be interested in knowing how I could create a BLCA-compatible database from the SILVA 23S LSU data - is this possible?

Very quick and dirty: 

https://drive.google.com/drive/folders/1t0TzC08y7_LyglsdihaXu27oWr7PiKLe

Took the LSU database (SILVA_132_LSURef_tax_silva.fasta), parsed fasta headers for species name, remapped against NCBI taxonomy using the ete3 toolkit, written out in BLCA format, backtranscribed RNA entries to DNA for the fasta file.

You'll need to:

`makeblastdb -in SILVA_132_LSURef_tax_silva_BLCAparsed.fasta -dbtype nucl -parse_seqids -out SILVA_132_LSURef_tax_silva_BLCAparsed.fasta`

There's lots of caveats, because the species name matching is imperfect and misses out chunks of things that the NCBI taxonomy can't handle, and this is entirely untested, and therefore use it at your own risk!

**Comment by qunfengdong** [comment]
Very helpful!  Thanks so much! We will give test it out and update github
instructions accordingly.
